FROM golang:1.25-alpine AS builder
ENV GOTOOLCHAIN=local
ARG DEMO_TARGET

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 go build -o /demo-bin ./demo/${DEMO_TARGET}/

FROM alpine:3.21
RUN apk add --no-cache ca-certificates
COPY --from=builder /demo-bin /demo-bin

ENTRYPOINT ["/demo-bin"]
