// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: cleanup.sql

package storeq

import (
	"context"
	"database/sql"
	"time"
)

const anonymizeAuditLogBefore = `-- name: AnonymizeAuditLogBefore :execrows
UPDATE audit_log
SET user_id = NULL
WHERE created_at < $1 AND user_id IS NOT NULL
`

func (q *Queries) AnonymizeAuditLogBefore(ctx context.Context, cutoff time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, anonymizeAuditLogBefore, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteExpiredAuthRequestsBefore = `-- name: DeleteExpiredAuthRequestsBefore :execrows
DELETE FROM auth_requests
WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredAuthRequestsBefore(ctx context.Context, cutoff time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredAuthRequestsBefore, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteExpiredDeviceCodesBefore = `-- name: DeleteExpiredDeviceCodesBefore :execrows
DELETE FROM device_codes
WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredDeviceCodesBefore(ctx context.Context, cutoff time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredDeviceCodesBefore, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteExpiredOrRevokedSessions = `-- name: DeleteExpiredOrRevokedSessions :execrows
DELETE FROM sessions
WHERE expires_at < $1 OR revoked_at IS NOT NULL
`

func (q *Queries) DeleteExpiredOrRevokedSessions(ctx context.Context, cutoff time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredOrRevokedSessions, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteExpiredRefreshTokensBefore = `-- name: DeleteExpiredRefreshTokensBefore :execrows
DELETE FROM refresh_tokens
WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredRefreshTokensBefore(ctx context.Context, cutoff time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredRefreshTokensBefore, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteRefreshTokensByUserID = `-- name: DeleteRefreshTokensByUserID :exec
DELETE FROM refresh_tokens
WHERE user_id = $1
`

func (q *Queries) DeleteRefreshTokensByUserID(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteRefreshTokensByUserID, userID)
	return err
}

const deleteRevokedRefreshTokensBefore = `-- name: DeleteRevokedRefreshTokensBefore :execrows
DELETE FROM refresh_tokens
WHERE revoked_at IS NOT NULL AND revoked_at < $1
`

func (q *Queries) DeleteRevokedRefreshTokensBefore(ctx context.Context, cutoff sql.NullTime) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRevokedRefreshTokensBefore, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSessionsByUserID = `-- name: DeleteSessionsByUserID :exec
DELETE FROM sessions
WHERE user_id = $1
`

func (q *Queries) DeleteSessionsByUserID(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionsByUserID, userID)
	return err
}

const deleteUserIdentitiesByUserID = `-- name: DeleteUserIdentitiesByUserID :exec
DELETE FROM user_identities
WHERE user_id = $1
`

func (q *Queries) DeleteUserIdentitiesByUserID(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserIdentitiesByUserID, userID)
	return err
}

const insertDeletionCompletedAudit = `-- name: InsertDeletionCompletedAudit :exec
INSERT INTO audit_log (user_id, event_type, created_at)
VALUES (NULLIF($1::text, '')::uuid, 'auth.deletion_completed', $2)
`

type InsertDeletionCompletedAuditParams struct {
	UserID    string
	CreatedAt time.Time
}

func (q *Queries) InsertDeletionCompletedAudit(ctx context.Context, arg InsertDeletionCompletedAuditParams) error {
	_, err := q.db.ExecContext(ctx, insertDeletionCompletedAudit, arg.UserID, arg.CreatedAt)
	return err
}

const listPendingDeletionUserIDsBefore = `-- name: ListPendingDeletionUserIDsBefore :many
SELECT id
FROM users
WHERE status = 'pending_deletion' AND deletion_scheduled_at < $1
`

func (q *Queries) ListPendingDeletionUserIDsBefore(ctx context.Context, cutoff sql.NullTime) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPendingDeletionUserIDsBefore, cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUserDeletedByID = `-- name: MarkUserDeletedByID :exec
UPDATE users SET
  email = 'deleted-' || id::text || '@deleted.invalid',
  name = NULL,
  avatar_url = NULL,
  status = 'deleted',
  deleted_at = $1,
  deletion_requested_at = NULL,
  deletion_scheduled_at = NULL
WHERE id = $2 AND status = 'pending_deletion' AND deletion_scheduled_at < $1
`

type MarkUserDeletedByIDParams struct {
	DeletedAt sql.NullTime
	UserID    string
}

func (q *Queries) MarkUserDeletedByID(ctx context.Context, arg MarkUserDeletedByIDParams) error {
	_, err := q.db.ExecContext(ctx, markUserDeletedByID, arg.DeletedAt, arg.UserID)
	return err
}
