// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package storeq

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type AuditLog struct {
	ID        int64
	UserID    uuid.NullUUID
	EventType string
	IpAddress pqtype.Inet
	UserAgent sql.NullString
	Metadata  pqtype.NullRawMessage
	CreatedAt time.Time
}

type AuthRequest struct {
	ID                  string
	ClientID            string
	Resource            sql.NullString
	RedirectUri         string
	Scopes              []string
	State               sql.NullString
	Nonce               sql.NullString
	CodeChallenge       sql.NullString
	CodeChallengeMethod sql.NullString
	Subject             sql.NullString
	AuthTime            sql.NullTime
	Done                bool
	Code                sql.NullString
	ExpiresAt           time.Time
	CreatedAt           time.Time
}

type DeviceCode struct {
	ID         string
	DeviceCode string
	UserCode   string
	ClientID   string
	Scopes     []string
	State      string
	Subject    sql.NullString
	ExpiresAt  time.Time
	AuthTime   sql.NullTime
	CreatedAt  time.Time
}

type RefreshToken struct {
	ID        string
	TokenHash string
	FamilyID  string
	UserID    string
	ClientID  string
	Resource  sql.NullString
	Scopes    []string
	ExpiresAt time.Time
	RevokedAt sql.NullTime
	UsedAt    sql.NullTime
	CreatedAt time.Time
}

type Session struct {
	ID        string
	UserID    string
	ExpiresAt time.Time
	RevokedAt sql.NullTime
	CreatedAt time.Time
}

type User struct {
	ID                  string
	Email               string
	EmailVerified       bool
	Name                sql.NullString
	AvatarUrl           sql.NullString
	Status              string
	DeletionRequestedAt sql.NullTime
	DeletionScheduledAt sql.NullTime
	DeletedAt           sql.NullTime
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type UserIdentity struct {
	ID             string
	UserID         string
	Provider       string
	ProviderUserID string
	ProviderEmail  sql.NullString
	ProviderRaw    pqtype.NullRawMessage
	CreatedAt      time.Time
}
