// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package storeq

import (
	"context"
)

type Querier interface {
	DeleteAuthRequestByID(ctx context.Context, id string) error
	GetAuthRequestByCode(ctx context.Context, dollar_1 string) (GetAuthRequestByCodeRow, error)
	GetAuthRequestByID(ctx context.Context, id string) (GetAuthRequestByIDRow, error)
	GetRefreshFamilyIDByTokenHash(ctx context.Context, tokenHash string) (string, error)
	GetRefreshTokenForUpdateByHash(ctx context.Context, tokenHash string) (GetRefreshTokenForUpdateByHashRow, error)
	GetRefreshTokenInfoByHashAndClientID(ctx context.Context, arg GetRefreshTokenInfoByHashAndClientIDParams) (GetRefreshTokenInfoByHashAndClientIDRow, error)
	GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error)
	GetUserByProviderIdentity(ctx context.Context, arg GetUserByProviderIdentityParams) (GetUserByProviderIdentityRow, error)
	GetUserForTxByID(ctx context.Context, id string) (GetUserForTxByIDRow, error)
	GetUserInfoFieldsByID(ctx context.Context, id string) (GetUserInfoFieldsByIDRow, error)
	InsertAuthRequest(ctx context.Context, arg InsertAuthRequestParams) error
	InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error
	InsertUser(ctx context.Context, arg InsertUserParams) error
	InsertUserIdentity(ctx context.Context, arg InsertUserIdentityParams) error
	MarkRefreshTokenUsedAndRevokedByID(ctx context.Context, arg MarkRefreshTokenUsedAndRevokedByIDParams) error
	RevokeRefreshFamily(ctx context.Context, arg RevokeRefreshFamilyParams) error
	RevokeRefreshTokenByHash(ctx context.Context, arg RevokeRefreshTokenByHashParams) (int64, error)
	RevokeRefreshTokenByIDText(ctx context.Context, arg RevokeRefreshTokenByIDTextParams) error
	UpdateAuthRequestCode(ctx context.Context, arg UpdateAuthRequestCodeParams) error
}

var _ Querier = (*Queries)(nil)
