// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package storeq

import (
	"context"
)

type Querier interface {
	GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error)
	GetUserByProviderIdentity(ctx context.Context, arg GetUserByProviderIdentityParams) (GetUserByProviderIdentityRow, error)
	GetUserForTxByID(ctx context.Context, id string) (GetUserForTxByIDRow, error)
	GetUserInfoFieldsByID(ctx context.Context, id string) (GetUserInfoFieldsByIDRow, error)
	InsertUser(ctx context.Context, arg InsertUserParams) error
	InsertUserIdentity(ctx context.Context, arg InsertUserIdentityParams) error
}

var _ Querier = (*Queries)(nil)
