// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: sessions.sql

package storeq

import (
	"context"
	"database/sql"
	"time"
)

const getValidSessionUser = `-- name: GetValidSessionUser :one
SELECT u.id, u.email, u.email_verified, u.name, u.avatar_url, u.status,
       u.created_at, u.updated_at
FROM sessions s
JOIN users u ON s.user_id = u.id
WHERE s.id = $1 AND s.expires_at > $2 AND s.revoked_at IS NULL
`

type GetValidSessionUserParams struct {
	ID        string
	ExpiresAt time.Time
}

type GetValidSessionUserRow struct {
	ID            string
	Email         string
	EmailVerified bool
	Name          sql.NullString
	AvatarUrl     sql.NullString
	Status        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) GetValidSessionUser(ctx context.Context, arg GetValidSessionUserParams) (GetValidSessionUserRow, error) {
	row := q.db.QueryRowContext(ctx, getValidSessionUser, arg.ID, arg.ExpiresAt)
	var i GetValidSessionUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.Name,
		&i.AvatarUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO sessions (id, user_id, expires_at, created_at)
VALUES ($1, $2, $3, $4)
`

type InsertSessionParams struct {
	ID        string
	UserID    string
	ExpiresAt time.Time
	CreatedAt time.Time
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.ExecContext(ctx, insertSession,
		arg.ID,
		arg.UserID,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const revokeSessionsByUserID = `-- name: RevokeSessionsByUserID :exec
UPDATE sessions
SET revoked_at = $1
WHERE user_id = $2 AND revoked_at IS NULL
`

type RevokeSessionsByUserIDParams struct {
	RevokedAt sql.NullTime
	UserID    string
}

func (q *Queries) RevokeSessionsByUserID(ctx context.Context, arg RevokeSessionsByUserIDParams) error {
	_, err := q.db.ExecContext(ctx, revokeSessionsByUserID, arg.RevokedAt, arg.UserID)
	return err
}
