// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package storeq

import (
	"context"
	"database/sql"
	"time"
)

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, email_verified, name, avatar_url, status,
       created_at, updated_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID            string
	Email         string
	EmailVerified bool
	Name          sql.NullString
	AvatarUrl     sql.NullString
	Status        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.Name,
		&i.AvatarUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByProviderIdentity = `-- name: GetUserByProviderIdentity :one
SELECT u.id, u.email, u.email_verified, u.name, u.avatar_url, u.status,
       u.created_at, u.updated_at
FROM users u
JOIN user_identities ui ON u.id = ui.user_id
WHERE ui.provider = $1 AND ui.provider_user_id = $2
`

type GetUserByProviderIdentityParams struct {
	Provider       string
	ProviderUserID string
}

type GetUserByProviderIdentityRow struct {
	ID            string
	Email         string
	EmailVerified bool
	Name          sql.NullString
	AvatarUrl     sql.NullString
	Status        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) GetUserByProviderIdentity(ctx context.Context, arg GetUserByProviderIdentityParams) (GetUserByProviderIdentityRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByProviderIdentity, arg.Provider, arg.ProviderUserID)
	var i GetUserByProviderIdentityRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.Name,
		&i.AvatarUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserForTxByID = `-- name: GetUserForTxByID :one
SELECT id, email, email_verified, name, status
FROM users
WHERE id = $1
`

type GetUserForTxByIDRow struct {
	ID            string
	Email         string
	EmailVerified bool
	Name          sql.NullString
	Status        string
}

func (q *Queries) GetUserForTxByID(ctx context.Context, id string) (GetUserForTxByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserForTxByID, id)
	var i GetUserForTxByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.Name,
		&i.Status,
	)
	return i, err
}

const getUserInfoFieldsByID = `-- name: GetUserInfoFieldsByID :one
SELECT id, email, email_verified, name
FROM users
WHERE id = $1
`

type GetUserInfoFieldsByIDRow struct {
	ID            string
	Email         string
	EmailVerified bool
	Name          sql.NullString
}

func (q *Queries) GetUserInfoFieldsByID(ctx context.Context, id string) (GetUserInfoFieldsByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserInfoFieldsByID, id)
	var i GetUserInfoFieldsByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.Name,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO users (id, email, email_verified, name, avatar_url, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, 'active', $6, $6)
`

type InsertUserParams struct {
	ID            string
	Email         string
	EmailVerified bool
	Name          sql.NullString
	AvatarUrl     sql.NullString
	CreatedAt     time.Time
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.ExecContext(ctx, insertUser,
		arg.ID,
		arg.Email,
		arg.EmailVerified,
		arg.Name,
		arg.AvatarUrl,
		arg.CreatedAt,
	)
	return err
}

const insertUserIdentity = `-- name: InsertUserIdentity :exec
INSERT INTO user_identities (id, user_id, provider, provider_user_id, provider_email, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertUserIdentityParams struct {
	ID             string
	UserID         string
	Provider       string
	ProviderUserID string
	ProviderEmail  sql.NullString
	CreatedAt      time.Time
}

func (q *Queries) InsertUserIdentity(ctx context.Context, arg InsertUserIdentityParams) error {
	_, err := q.db.ExecContext(ctx, insertUserIdentity,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserID,
		arg.ProviderEmail,
		arg.CreatedAt,
	)
	return err
}
