// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account_keys.sql

package storeq

import (
	"context"
	"database/sql"
	"time"
)

const destroyAccountEncryptionKey = `-- name: DestroyAccountEncryptionKey :execrows
UPDATE account_encryption_keys
SET wrapped_dek = NULL,
    destroyed_at = $1
WHERE account_id = $2 AND destroyed_at IS NULL
`

type DestroyAccountEncryptionKeyParams struct {
	DestroyedAt sql.NullTime
	AccountID   string
}

func (q *Queries) DestroyAccountEncryptionKey(ctx context.Context, arg DestroyAccountEncryptionKeyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, destroyAccountEncryptionKey, arg.DestroyedAt, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAccountEncryptionKey = `-- name: GetAccountEncryptionKey :one
SELECT wrapped_dek, kek_id, kek_version, destroyed_at
FROM account_encryption_keys
WHERE account_id = $1
`

type GetAccountEncryptionKeyRow struct {
	WrappedDek  []byte
	KekID       string
	KekVersion  string
	DestroyedAt sql.NullTime
}

func (q *Queries) GetAccountEncryptionKey(ctx context.Context, accountID string) (GetAccountEncryptionKeyRow, error) {
	row := q.db.QueryRowContext(ctx, getAccountEncryptionKey, accountID)
	var i GetAccountEncryptionKeyRow
	err := row.Scan(
		&i.WrappedDek,
		&i.KekID,
		&i.KekVersion,
		&i.DestroyedAt,
	)
	return i, err
}

const insertAccountEncryptionKey = `-- name: InsertAccountEncryptionKey :exec
INSERT INTO account_encryption_keys (account_id, wrapped_dek, kek_id, kek_version, created_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (account_id) DO NOTHING
`

type InsertAccountEncryptionKeyParams struct {
	AccountID  string
	WrappedDek []byte
	KekID      string
	KekVersion string
	CreatedAt  time.Time
}

func (q *Queries) InsertAccountEncryptionKey(ctx context.Context, arg InsertAccountEncryptionKeyParams) error {
	_, err := q.db.ExecContext(ctx, insertAccountEncryptionKey,
		arg.AccountID,
		arg.WrappedDek,
		arg.KekID,
		arg.KekVersion,
		arg.CreatedAt,
	)
	return err
}
