// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: audit_log.sql

package storeq

import (
	"context"
	"encoding/json"
	"time"
)

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log (user_id, event_type, ip_address, user_agent, metadata, created_at)
VALUES (
  NULLIF($1::text, '')::uuid,
  $2,
  NULLIF($3, '')::inet,
  NULLIF($4, ''),
  $5::jsonb,
  $6
)
`

type InsertAuditLogParams struct {
	UserID    string
	EventType string
	IpAddress interface{}
	UserAgent interface{}
	Metadata  json.RawMessage
	CreatedAt time.Time
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, insertAuditLog,
		arg.UserID,
		arg.EventType,
		arg.IpAddress,
		arg.UserAgent,
		arg.Metadata,
		arg.CreatedAt,
	)
	return err
}
