// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_log.sql

package storeq

import (
	"context"
	"encoding/json"
	"time"
)

const getAuditClientContextBySessionID = `-- name: GetAuditClientContextBySessionID :one
SELECT
  COALESCE(metadata->>'client_id', '')::text AS client_id,
  COALESCE(metadata->>'client_name', '')::text AS client_name
FROM audit_log
WHERE user_id = NULLIF($1::text, '')::uuid
  AND event_type = 'auth.login'
  AND metadata->>'session_id' = $2::text
ORDER BY created_at DESC
LIMIT 1
`

type GetAuditClientContextBySessionIDParams struct {
	UserID    string
	SessionID string
}

type GetAuditClientContextBySessionIDRow struct {
	ClientID   string
	ClientName string
}

func (q *Queries) GetAuditClientContextBySessionID(ctx context.Context, arg GetAuditClientContextBySessionIDParams) (GetAuditClientContextBySessionIDRow, error) {
	row := q.db.QueryRowContext(ctx, getAuditClientContextBySessionID, arg.UserID, arg.SessionID)
	var i GetAuditClientContextBySessionIDRow
	err := row.Scan(&i.ClientID, &i.ClientName)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log (user_id, event_type, ip_address, user_agent, metadata, created_at)
VALUES (
  NULLIF($1::text, '')::uuid,
  $2,
  NULLIF($3, '')::inet,
  NULLIF($4, ''),
  $5::jsonb,
  $6
)
`

type InsertAuditLogParams struct {
	UserID    string
	EventType string
	IpAddress interface{}
	UserAgent interface{}
	Metadata  json.RawMessage
	CreatedAt time.Time
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, insertAuditLog,
		arg.UserID,
		arg.EventType,
		arg.IpAddress,
		arg.UserAgent,
		arg.Metadata,
		arg.CreatedAt,
	)
	return err
}
