// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: auth_requests.sql

package storeq

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
)

const deleteAuthRequestByID = `-- name: DeleteAuthRequestByID :exec
DELETE FROM auth_requests
WHERE id = $1
`

func (q *Queries) DeleteAuthRequestByID(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAuthRequestByID, id)
	return err
}

const getAuthRequestByCode = `-- name: GetAuthRequestByCode :one
SELECT id,
       client_id,
       COALESCE(resource, '') AS resource,
       redirect_uri,
       scopes,
       COALESCE(state, '') AS state,
       COALESCE(nonce, '') AS nonce,
       COALESCE(code_challenge, '') AS code_challenge,
       COALESCE(code_challenge_method, '') AS code_challenge_method,
       subject,
       auth_time,
       done,
       code,
       expires_at,
       created_at
FROM auth_requests
WHERE code = $1::text
`

type GetAuthRequestByCodeRow struct {
	ID                  string
	ClientID            string
	Resource            string
	RedirectUri         string
	Scopes              []string
	State               string
	Nonce               string
	CodeChallenge       string
	CodeChallengeMethod string
	Subject             sql.NullString
	AuthTime            sql.NullTime
	Done                bool
	Code                sql.NullString
	ExpiresAt           time.Time
	CreatedAt           time.Time
}

func (q *Queries) GetAuthRequestByCode(ctx context.Context, dollar_1 string) (GetAuthRequestByCodeRow, error) {
	row := q.db.QueryRowContext(ctx, getAuthRequestByCode, dollar_1)
	var i GetAuthRequestByCodeRow
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Resource,
		&i.RedirectUri,
		pq.Array(&i.Scopes),
		&i.State,
		&i.Nonce,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.Subject,
		&i.AuthTime,
		&i.Done,
		&i.Code,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAuthRequestByID = `-- name: GetAuthRequestByID :one
SELECT id,
       client_id,
       COALESCE(resource, '') AS resource,
       redirect_uri,
       scopes,
       COALESCE(state, '') AS state,
       COALESCE(nonce, '') AS nonce,
       COALESCE(code_challenge, '') AS code_challenge,
       COALESCE(code_challenge_method, '') AS code_challenge_method,
       subject,
       auth_time,
       done,
       code,
       expires_at,
       created_at
FROM auth_requests
WHERE id = $1
`

type GetAuthRequestByIDRow struct {
	ID                  string
	ClientID            string
	Resource            string
	RedirectUri         string
	Scopes              []string
	State               string
	Nonce               string
	CodeChallenge       string
	CodeChallengeMethod string
	Subject             sql.NullString
	AuthTime            sql.NullTime
	Done                bool
	Code                sql.NullString
	ExpiresAt           time.Time
	CreatedAt           time.Time
}

func (q *Queries) GetAuthRequestByID(ctx context.Context, id string) (GetAuthRequestByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getAuthRequestByID, id)
	var i GetAuthRequestByIDRow
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Resource,
		&i.RedirectUri,
		pq.Array(&i.Scopes),
		&i.State,
		&i.Nonce,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.Subject,
		&i.AuthTime,
		&i.Done,
		&i.Code,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertAuthRequest = `-- name: InsertAuthRequest :exec
INSERT INTO auth_requests (
  id, client_id, resource, redirect_uri, scopes, state, nonce,
  code_challenge, code_challenge_method, expires_at, created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type InsertAuthRequestParams struct {
	ID                  string
	ClientID            string
	Resource            sql.NullString
	RedirectUri         string
	Scopes              []string
	State               sql.NullString
	Nonce               sql.NullString
	CodeChallenge       sql.NullString
	CodeChallengeMethod sql.NullString
	ExpiresAt           time.Time
	CreatedAt           time.Time
}

func (q *Queries) InsertAuthRequest(ctx context.Context, arg InsertAuthRequestParams) error {
	_, err := q.db.ExecContext(ctx, insertAuthRequest,
		arg.ID,
		arg.ClientID,
		arg.Resource,
		arg.RedirectUri,
		pq.Array(arg.Scopes),
		arg.State,
		arg.Nonce,
		arg.CodeChallenge,
		arg.CodeChallengeMethod,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const updateAuthRequestCode = `-- name: UpdateAuthRequestCode :exec
UPDATE auth_requests
SET code = $1
WHERE id = $2
`

type UpdateAuthRequestCodeParams struct {
	Code sql.NullString
	ID   string
}

func (q *Queries) UpdateAuthRequestCode(ctx context.Context, arg UpdateAuthRequestCodeParams) error {
	_, err := q.db.ExecContext(ctx, updateAuthRequestCode, arg.Code, arg.ID)
	return err
}
