// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cleanup.sql

package storeq

import (
	"context"
	"database/sql"
	"time"
)

const anonymizeAuditLogBefore = `-- name: AnonymizeAuditLogBefore :execrows
UPDATE audit_log
SET user_id = NULL,
    ip_address = NULL,
    user_agent = NULL
WHERE created_at < $1
  AND (user_id IS NOT NULL OR ip_address IS NOT NULL OR user_agent IS NOT NULL)
`

func (q *Queries) AnonymizeAuditLogBefore(ctx context.Context, cutoff time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, anonymizeAuditLogBefore, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteExpiredAuthRequestsBefore = `-- name: DeleteExpiredAuthRequestsBefore :execrows
DELETE FROM auth_requests
WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredAuthRequestsBefore(ctx context.Context, cutoff time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredAuthRequestsBefore, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteExpiredDeviceCodesBefore = `-- name: DeleteExpiredDeviceCodesBefore :execrows
DELETE FROM device_codes
WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredDeviceCodesBefore(ctx context.Context, cutoff time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredDeviceCodesBefore, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteExpiredOrRevokedSessions = `-- name: DeleteExpiredOrRevokedSessions :execrows
DELETE FROM sessions
WHERE expires_at < $1 OR revoked_at IS NOT NULL
`

func (q *Queries) DeleteExpiredOrRevokedSessions(ctx context.Context, cutoff time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredOrRevokedSessions, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteExpiredRefreshTokensBefore = `-- name: DeleteExpiredRefreshTokensBefore :execrows
DELETE FROM refresh_tokens
WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredRefreshTokensBefore(ctx context.Context, cutoff time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredRefreshTokensBefore, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteRefreshTokensByUserID = `-- name: DeleteRefreshTokensByUserID :exec
DELETE FROM refresh_tokens
WHERE user_id = $1
`

func (q *Queries) DeleteRefreshTokensByUserID(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteRefreshTokensByUserID, userID)
	return err
}

const deleteRevokedRefreshTokensBefore = `-- name: DeleteRevokedRefreshTokensBefore :execrows
DELETE FROM refresh_tokens
WHERE revoked_at IS NOT NULL AND revoked_at < $1
`

func (q *Queries) DeleteRevokedRefreshTokensBefore(ctx context.Context, cutoff sql.NullTime) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRevokedRefreshTokensBefore, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSessionsByUserID = `-- name: DeleteSessionsByUserID :exec
DELETE FROM sessions
WHERE user_id = $1
`

func (q *Queries) DeleteSessionsByUserID(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionsByUserID, userID)
	return err
}

const deleteUserIdentitiesByUserID = `-- name: DeleteUserIdentitiesByUserID :exec
DELETE FROM user_identities
WHERE user_id = $1
`

func (q *Queries) DeleteUserIdentitiesByUserID(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserIdentitiesByUserID, userID)
	return err
}

const insertDeletionCompletedAudit = `-- name: InsertDeletionCompletedAudit :exec
INSERT INTO audit_log (user_id, event_type, metadata, created_at)
VALUES (
  NULLIF($1::text, '')::uuid,
  'auth.deletion_completed',
  jsonb_build_object('reason', $2::text),
  $3
)
`

type InsertDeletionCompletedAuditParams struct {
	UserID    string
	Reason    string
	CreatedAt time.Time
}

func (q *Queries) InsertDeletionCompletedAudit(ctx context.Context, arg InsertDeletionCompletedAuditParams) error {
	_, err := q.db.ExecContext(ctx, insertDeletionCompletedAudit, arg.UserID, arg.Reason, arg.CreatedAt)
	return err
}

const listPendingDeletionUserIDsBefore = `-- name: ListPendingDeletionUserIDsBefore :many
SELECT id
FROM users
WHERE status = 'pending_deletion' AND deletion_scheduled_at < $1
`

func (q *Queries) ListPendingDeletionUserIDsBefore(ctx context.Context, cutoff sql.NullTime) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPendingDeletionUserIDsBefore, cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUserDeletedByID = `-- name: MarkUserDeletedByID :execrows
UPDATE users SET
  email = 'deleted-' || id::text || '@deleted.invalid',
  name = NULL,
  email_ciphertext = NULL, email_nonce = NULL, email_enc_key_id = NULL, email_enc_version = NULL,
  email_hash = NULL, email_hash_key_id = NULL, email_hash_version = NULL,
  name_ciphertext = NULL, name_nonce = NULL, name_enc_key_id = NULL, name_enc_version = NULL,
  status = 'deleted',
  deleted_at = $1,
  deletion_requested_at = NULL,
  deletion_scheduled_at = NULL
WHERE id = $2 AND status = 'pending_deletion' AND deletion_scheduled_at < $1
`

type MarkUserDeletedByIDParams struct {
	DeletedAt sql.NullTime
	UserID    string
}

// PII redaction on deletion (ADR-002): the plaintext tombstone replaces email,
// and every encrypted/hashed email/name column is cleared so no recoverable PII
// remains for the deleted user.
func (q *Queries) MarkUserDeletedByID(ctx context.Context, arg MarkUserDeletedByIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markUserDeletedByID, arg.DeletedAt, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const redactAuditLogPIIByUserID = `-- name: RedactAuditLogPIIByUserID :execrows
UPDATE audit_log
SET ip_address = NULL,
    user_agent = NULL
WHERE user_id = NULLIF($1::text, '')::uuid
  AND (ip_address IS NOT NULL OR user_agent IS NOT NULL)
`

func (q *Queries) RedactAuditLogPIIByUserID(ctx context.Context, userID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, redactAuditLogPIIByUserID, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const tryCleanupAdvisoryLock = `-- name: TryCleanupAdvisoryLock :one
SELECT pg_try_advisory_lock($1::bigint)
`

func (q *Queries) TryCleanupAdvisoryLock(ctx context.Context, lockKey int64) (bool, error) {
	row := q.db.QueryRowContext(ctx, tryCleanupAdvisoryLock, lockKey)
	var pg_try_advisory_lock bool
	err := row.Scan(&pg_try_advisory_lock)
	return pg_try_advisory_lock, err
}

const unlockCleanupAdvisoryLock = `-- name: UnlockCleanupAdvisoryLock :one
SELECT pg_advisory_unlock($1::bigint)
`

func (q *Queries) UnlockCleanupAdvisoryLock(ctx context.Context, lockKey int64) (bool, error) {
	row := q.db.QueryRowContext(ctx, unlockCleanupAdvisoryLock, lockKey)
	var pg_advisory_unlock bool
	err := row.Scan(&pg_advisory_unlock)
	return pg_advisory_unlock, err
}
