// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: cleanup.sql

package storeq

import (
	"context"
	"database/sql"
	"time"
)

const anonymizeAuditLogBatch = `-- name: AnonymizeAuditLogBatch :execrows
WITH target AS (
    SELECT id
    FROM audit_log
    WHERE audit_log.created_at < $1 AND audit_log.user_id IS NOT NULL
    LIMIT $2
)
UPDATE audit_log a
SET user_id = NULL
FROM target t
WHERE a.id = t.id
`

type AnonymizeAuditLogBatchParams struct {
	Cutoff    time.Time
	BatchSize int32
}

func (q *Queries) AnonymizeAuditLogBatch(ctx context.Context, arg AnonymizeAuditLogBatchParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, anonymizeAuditLogBatch, arg.Cutoff, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteExpiredAuthRequestsBatch = `-- name: DeleteExpiredAuthRequestsBatch :execrows
WITH doomed AS (
    SELECT id
    FROM auth_requests
    WHERE auth_requests.expires_at < $1
    LIMIT $2
)
DELETE FROM auth_requests t
USING doomed d
WHERE t.id = d.id
`

type DeleteExpiredAuthRequestsBatchParams struct {
	Cutoff    time.Time
	BatchSize int32
}

func (q *Queries) DeleteExpiredAuthRequestsBatch(ctx context.Context, arg DeleteExpiredAuthRequestsBatchParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredAuthRequestsBatch, arg.Cutoff, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteExpiredDeviceCodesBatch = `-- name: DeleteExpiredDeviceCodesBatch :execrows
WITH doomed AS (
    SELECT id
    FROM device_codes
    WHERE device_codes.expires_at < $1
    LIMIT $2
)
DELETE FROM device_codes t
USING doomed d
WHERE t.id = d.id
`

type DeleteExpiredDeviceCodesBatchParams struct {
	Cutoff    time.Time
	BatchSize int32
}

func (q *Queries) DeleteExpiredDeviceCodesBatch(ctx context.Context, arg DeleteExpiredDeviceCodesBatchParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredDeviceCodesBatch, arg.Cutoff, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteExpiredOrRevokedSessionsBatch = `-- name: DeleteExpiredOrRevokedSessionsBatch :execrows
WITH doomed AS (
    SELECT id
    FROM sessions
    WHERE sessions.expires_at < $1 OR sessions.revoked_at IS NOT NULL
    LIMIT $2
)
DELETE FROM sessions t
USING doomed d
WHERE t.id = d.id
`

type DeleteExpiredOrRevokedSessionsBatchParams struct {
	Cutoff    time.Time
	BatchSize int32
}

func (q *Queries) DeleteExpiredOrRevokedSessionsBatch(ctx context.Context, arg DeleteExpiredOrRevokedSessionsBatchParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredOrRevokedSessionsBatch, arg.Cutoff, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteExpiredRefreshTokensBatch = `-- name: DeleteExpiredRefreshTokensBatch :execrows
WITH doomed AS (
    SELECT id
    FROM refresh_tokens
    WHERE refresh_tokens.expires_at < $1
    LIMIT $2
)
DELETE FROM refresh_tokens t
USING doomed d
WHERE t.id = d.id
`

type DeleteExpiredRefreshTokensBatchParams struct {
	Cutoff    time.Time
	BatchSize int32
}

func (q *Queries) DeleteExpiredRefreshTokensBatch(ctx context.Context, arg DeleteExpiredRefreshTokensBatchParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredRefreshTokensBatch, arg.Cutoff, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteRefreshTokensByUserID = `-- name: DeleteRefreshTokensByUserID :exec
DELETE FROM refresh_tokens
WHERE user_id = $1
`

func (q *Queries) DeleteRefreshTokensByUserID(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteRefreshTokensByUserID, userID)
	return err
}

const deleteRevokedRefreshTokensBatch = `-- name: DeleteRevokedRefreshTokensBatch :execrows
WITH doomed AS (
    SELECT id
    FROM refresh_tokens
    WHERE refresh_tokens.revoked_at IS NOT NULL AND refresh_tokens.revoked_at < $1
    LIMIT $2
)
DELETE FROM refresh_tokens t
USING doomed d
WHERE t.id = d.id
`

type DeleteRevokedRefreshTokensBatchParams struct {
	Cutoff    sql.NullTime
	BatchSize int32
}

func (q *Queries) DeleteRevokedRefreshTokensBatch(ctx context.Context, arg DeleteRevokedRefreshTokensBatchParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRevokedRefreshTokensBatch, arg.Cutoff, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSessionsByUserID = `-- name: DeleteSessionsByUserID :exec
DELETE FROM sessions
WHERE user_id = $1
`

func (q *Queries) DeleteSessionsByUserID(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionsByUserID, userID)
	return err
}

const deleteUserIdentitiesByUserID = `-- name: DeleteUserIdentitiesByUserID :exec
DELETE FROM user_identities
WHERE user_id = $1
`

func (q *Queries) DeleteUserIdentitiesByUserID(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserIdentitiesByUserID, userID)
	return err
}

const insertDeletionCompletedAudit = `-- name: InsertDeletionCompletedAudit :exec
INSERT INTO audit_log (user_id, event_type, created_at)
VALUES (NULLIF($1::text, '')::uuid, 'auth.deletion_completed', $2)
`

type InsertDeletionCompletedAuditParams struct {
	UserID    string
	CreatedAt time.Time
}

func (q *Queries) InsertDeletionCompletedAudit(ctx context.Context, arg InsertDeletionCompletedAuditParams) error {
	_, err := q.db.ExecContext(ctx, insertDeletionCompletedAudit, arg.UserID, arg.CreatedAt)
	return err
}

const listPendingDeletionUserIDsBefore = `-- name: ListPendingDeletionUserIDsBefore :many
SELECT id
FROM users
WHERE status = 'pending_deletion' AND deletion_scheduled_at < $1
`

func (q *Queries) ListPendingDeletionUserIDsBefore(ctx context.Context, cutoff sql.NullTime) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPendingDeletionUserIDsBefore, cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUserDeletedByID = `-- name: MarkUserDeletedByID :exec
UPDATE users SET
  email = 'deleted-' || id::text || '@deleted.invalid',
  name = NULL,
  avatar_url = NULL,
  status = 'deleted',
  deleted_at = $1,
  deletion_requested_at = NULL,
  deletion_scheduled_at = NULL
WHERE id = $2 AND status = 'pending_deletion' AND deletion_scheduled_at < $1
`

type MarkUserDeletedByIDParams struct {
	DeletedAt sql.NullTime
	UserID    string
}

func (q *Queries) MarkUserDeletedByID(ctx context.Context, arg MarkUserDeletedByIDParams) error {
	_, err := q.db.ExecContext(ctx, markUserDeletedByID, arg.DeletedAt, arg.UserID)
	return err
}
