// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: console.sql

package storeq

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/lib/pq"
)

const countAuditLogByUserID = `-- name: CountAuditLogByUserID :one
SELECT COUNT(*)
FROM audit_log
WHERE audit_log.user_id = NULLIF($1::text, '')::uuid
`

func (q *Queries) CountAuditLogByUserID(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAuditLogByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getActiveConnectionsByUserID = `-- name: GetActiveConnectionsByUserID :many
WITH active_tokens AS (
  SELECT DISTINCT ON (client_id)
         client_id,
         scopes
  FROM refresh_tokens
  WHERE refresh_tokens.user_id = $1
    AND refresh_tokens.revoked_at IS NULL
    AND refresh_tokens.expires_at > $2
  ORDER BY refresh_tokens.client_id, refresh_tokens.created_at DESC
),
last_used_tokens AS (
  SELECT client_id,
         MAX(used_at)::timestamptz AS last_used
  FROM refresh_tokens
  WHERE refresh_tokens.user_id = $1
    AND refresh_tokens.used_at IS NOT NULL
  GROUP BY refresh_tokens.client_id
)
SELECT active_tokens.client_id,
       active_tokens.scopes,
       last_used_tokens.last_used
FROM active_tokens
LEFT JOIN last_used_tokens ON last_used_tokens.client_id = active_tokens.client_id
ORDER BY active_tokens.client_id
`

type GetActiveConnectionsByUserIDParams struct {
	UserID    string
	ExpiresAt time.Time
}

type GetActiveConnectionsByUserIDRow struct {
	ClientID string
	Scopes   []string
	LastUsed sql.NullTime
}

func (q *Queries) GetActiveConnectionsByUserID(ctx context.Context, arg GetActiveConnectionsByUserIDParams) ([]GetActiveConnectionsByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getActiveConnectionsByUserID, arg.UserID, arg.ExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveConnectionsByUserIDRow
	for rows.Next() {
		var i GetActiveConnectionsByUserIDRow
		if err := rows.Scan(&i.ClientID, pq.Array(&i.Scopes), &i.LastUsed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveSessionsByUserID = `-- name: GetActiveSessionsByUserID :many
SELECT s.id,
       s.expires_at,
       COALESCE(login.ip_address::text, '')::text AS ip_address,
       COALESCE(login.user_agent, '')::text AS user_agent,
       COALESCE(login.created_at, s.created_at) AS created_at
FROM sessions s
LEFT JOIN LATERAL (
  SELECT audit_log.ip_address,
         audit_log.user_agent,
         audit_log.created_at
  FROM audit_log
  WHERE audit_log.user_id = s.user_id
    AND audit_log.event_type = 'auth.login'
    AND audit_log.metadata->>'session_id' = s.id::text
  ORDER BY audit_log.created_at DESC
  LIMIT 1
) login ON true
WHERE s.user_id = $1
  AND s.expires_at > $2
  AND s.revoked_at IS NULL
ORDER BY s.created_at DESC
`

type GetActiveSessionsByUserIDParams struct {
	UserID    string
	ExpiresAt time.Time
}

type GetActiveSessionsByUserIDRow struct {
	ID        string
	ExpiresAt time.Time
	IpAddress string
	UserAgent string
	CreatedAt time.Time
}

func (q *Queries) GetActiveSessionsByUserID(ctx context.Context, arg GetActiveSessionsByUserIDParams) ([]GetActiveSessionsByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getActiveSessionsByUserID, arg.UserID, arg.ExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveSessionsByUserIDRow
	for rows.Next() {
		var i GetActiveSessionsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ExpiresAt,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuditLogByUserID = `-- name: GetAuditLogByUserID :many
SELECT id,
       event_type,
       COALESCE(ip_address::text, '')::text AS ip_address,
       COALESCE(user_agent, '')::text AS user_agent,
       COALESCE(metadata, '{}'::jsonb)::jsonb AS metadata,
       created_at,
       COUNT(*) OVER() AS total
FROM audit_log
WHERE audit_log.user_id = NULLIF($1::text, '')::uuid
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type GetAuditLogByUserIDParams struct {
	UserID     string
	PageOffset int32
	PageLimit  int32
}

type GetAuditLogByUserIDRow struct {
	ID        int64
	EventType string
	IpAddress string
	UserAgent string
	Metadata  json.RawMessage
	CreatedAt time.Time
	Total     int64
}

func (q *Queries) GetAuditLogByUserID(ctx context.Context, arg GetAuditLogByUserIDParams) ([]GetAuditLogByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getAuditLogByUserID, arg.UserID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAuditLogByUserIDRow
	for rows.Next() {
		var i GetAuditLogByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.IpAddress,
			&i.UserAgent,
			&i.Metadata,
			&i.CreatedAt,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeActiveRefreshTokensByUserIDAndClientID = `-- name: RevokeActiveRefreshTokensByUserIDAndClientID :exec
UPDATE refresh_tokens
SET revoked_at = $1
WHERE refresh_tokens.user_id = $2
  AND refresh_tokens.client_id = $3
  AND refresh_tokens.revoked_at IS NULL
`

type RevokeActiveRefreshTokensByUserIDAndClientIDParams struct {
	RevokedAt sql.NullTime
	UserID    string
	ClientID  string
}

func (q *Queries) RevokeActiveRefreshTokensByUserIDAndClientID(ctx context.Context, arg RevokeActiveRefreshTokensByUserIDAndClientIDParams) error {
	_, err := q.db.ExecContext(ctx, revokeActiveRefreshTokensByUserIDAndClientID, arg.RevokedAt, arg.UserID, arg.ClientID)
	return err
}

const revokeOtherActiveSessionsByUserID = `-- name: RevokeOtherActiveSessionsByUserID :exec
UPDATE sessions
SET revoked_at = $1
WHERE sessions.user_id = $2
  AND sessions.id <> $3
  AND sessions.expires_at > $4
  AND sessions.revoked_at IS NULL
`

type RevokeOtherActiveSessionsByUserIDParams struct {
	RevokedAt sql.NullTime
	UserID    string
	ID        string
	ExpiresAt time.Time
}

func (q *Queries) RevokeOtherActiveSessionsByUserID(ctx context.Context, arg RevokeOtherActiveSessionsByUserIDParams) error {
	_, err := q.db.ExecContext(ctx, revokeOtherActiveSessionsByUserID,
		arg.RevokedAt,
		arg.UserID,
		arg.ID,
		arg.ExpiresAt,
	)
	return err
}

const revokeSessionByUserIDAndID = `-- name: RevokeSessionByUserIDAndID :exec
UPDATE sessions
SET revoked_at = $1
WHERE sessions.user_id = $2
  AND sessions.id = $3
  AND sessions.revoked_at IS NULL
`

type RevokeSessionByUserIDAndIDParams struct {
	RevokedAt sql.NullTime
	UserID    string
	ID        string
}

func (q *Queries) RevokeSessionByUserIDAndID(ctx context.Context, arg RevokeSessionByUserIDAndIDParams) error {
	_, err := q.db.ExecContext(ctx, revokeSessionByUserIDAndID, arg.RevokedAt, arg.UserID, arg.ID)
	return err
}
