// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: console.sql

package storeq

import (
	"context"
	"time"
)

const getActiveConnectionsByUserID = `-- name: GetActiveConnectionsByUserID :many
SELECT DISTINCT client_id
FROM refresh_tokens
WHERE user_id = $1
  AND revoked_at IS NULL
  AND expires_at > $2
ORDER BY client_id
`

type GetActiveConnectionsByUserIDParams struct {
	UserID    string
	ExpiresAt time.Time
}

func (q *Queries) GetActiveConnectionsByUserID(ctx context.Context, arg GetActiveConnectionsByUserIDParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getActiveConnectionsByUserID, arg.UserID, arg.ExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var client_id string
		if err := rows.Scan(&client_id); err != nil {
			return nil, err
		}
		items = append(items, client_id)
	}
	return items, rows.Err()
}
