// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: crypto_key_epochs.sql

package storeq

import (
	"context"
	"time"
)

const getActiveEpoch = `-- name: GetActiveEpoch :one
SELECT key_id, verify_tag, version
FROM crypto_key_epochs
WHERE domain = $1 AND status = 'active'
`

type GetActiveEpochRow struct {
	KeyID     string
	VerifyTag string
	Version   int32
}

func (q *Queries) GetActiveEpoch(ctx context.Context, domain string) (GetActiveEpochRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveEpoch, domain)
	var i GetActiveEpochRow
	err := row.Scan(&i.KeyID, &i.VerifyTag, &i.Version)
	return i, err
}

const insertActiveEpoch = `-- name: InsertActiveEpoch :exec
INSERT INTO crypto_key_epochs (key_id, domain, status, verify_tag, version, created_at, activated_at)
VALUES ($1, $2, 'active', $3, 1, $4, $4)
ON CONFLICT DO NOTHING
`

type InsertActiveEpochParams struct {
	KeyID     string
	Domain    string
	VerifyTag string
	CreatedAt time.Time
}

func (q *Queries) InsertActiveEpoch(ctx context.Context, arg InsertActiveEpochParams) error {
	_, err := q.db.ExecContext(ctx, insertActiveEpoch,
		arg.KeyID,
		arg.Domain,
		arg.VerifyTag,
		arg.CreatedAt,
	)
	return err
}
