// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: device_codes.sql

package storeq

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
)

const approveDeviceCodeByUserCode = `-- name: ApproveDeviceCodeByUserCode :execrows
UPDATE device_codes
SET state = 'approved', subject = $1, auth_time = $2
WHERE user_code = $3 AND state = 'pending' AND expires_at > $2
`

type ApproveDeviceCodeByUserCodeParams struct {
	Subject  sql.NullString
	AuthTime sql.NullTime
	UserCode string
}

func (q *Queries) ApproveDeviceCodeByUserCode(ctx context.Context, arg ApproveDeviceCodeByUserCodeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, approveDeviceCodeByUserCode, arg.Subject, arg.AuthTime, arg.UserCode)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const denyDeviceCodeByUserCode = `-- name: DenyDeviceCodeByUserCode :execrows
UPDATE device_codes
SET state = 'denied'
WHERE user_code = $1 AND state = 'pending' AND expires_at > $2
`

type DenyDeviceCodeByUserCodeParams struct {
	UserCode string
	Now      time.Time
}

func (q *Queries) DenyDeviceCodeByUserCode(ctx context.Context, arg DenyDeviceCodeByUserCodeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, denyDeviceCodeByUserCode, arg.UserCode, arg.Now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getDeviceAuthorizationForUpdate = `-- name: GetDeviceAuthorizationForUpdate :one
SELECT id, client_id, scopes, state, subject, expires_at, auth_time
FROM device_codes
WHERE device_code = $1 AND client_id = $2
FOR UPDATE
`

type GetDeviceAuthorizationForUpdateParams struct {
	DeviceCode string
	ClientID   string
}

type GetDeviceAuthorizationForUpdateRow struct {
	ID        string
	ClientID  string
	Scopes    []string
	State     string
	Subject   sql.NullString
	ExpiresAt time.Time
	AuthTime  sql.NullTime
}

func (q *Queries) GetDeviceAuthorizationForUpdate(ctx context.Context, arg GetDeviceAuthorizationForUpdateParams) (GetDeviceAuthorizationForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getDeviceAuthorizationForUpdate, arg.DeviceCode, arg.ClientID)
	var i GetDeviceAuthorizationForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		pq.Array(&i.Scopes),
		&i.State,
		&i.Subject,
		&i.ExpiresAt,
		&i.AuthTime,
	)
	return i, err
}

const getDeviceCodeByUserCode = `-- name: GetDeviceCodeByUserCode :one
SELECT id, device_code, user_code, client_id, scopes, state, subject, expires_at, auth_time
FROM device_codes
WHERE user_code = $1
`

type GetDeviceCodeByUserCodeRow struct {
	ID         string
	DeviceCode string
	UserCode   string
	ClientID   string
	Scopes     []string
	State      string
	Subject    sql.NullString
	ExpiresAt  time.Time
	AuthTime   sql.NullTime
}

func (q *Queries) GetDeviceCodeByUserCode(ctx context.Context, userCode string) (GetDeviceCodeByUserCodeRow, error) {
	row := q.db.QueryRowContext(ctx, getDeviceCodeByUserCode, userCode)
	var i GetDeviceCodeByUserCodeRow
	err := row.Scan(
		&i.ID,
		&i.DeviceCode,
		&i.UserCode,
		&i.ClientID,
		pq.Array(&i.Scopes),
		&i.State,
		&i.Subject,
		&i.ExpiresAt,
		&i.AuthTime,
	)
	return i, err
}

const insertDeviceCode = `-- name: InsertDeviceCode :exec
INSERT INTO device_codes (id, device_code, user_code, client_id, scopes, state, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5, 'pending', $6, $7)
`

type InsertDeviceCodeParams struct {
	ID         string
	DeviceCode string
	UserCode   string
	ClientID   string
	Scopes     []string
	ExpiresAt  time.Time
	CreatedAt  time.Time
}

func (q *Queries) InsertDeviceCode(ctx context.Context, arg InsertDeviceCodeParams) error {
	_, err := q.db.ExecContext(ctx, insertDeviceCode,
		arg.ID,
		arg.DeviceCode,
		arg.UserCode,
		arg.ClientID,
		pq.Array(arg.Scopes),
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const updateDeviceCodeStateConsumedByID = `-- name: UpdateDeviceCodeStateConsumedByID :exec
UPDATE device_codes
SET state = 'consumed'
WHERE id = $1
`

func (q *Queries) UpdateDeviceCodeStateConsumedByID(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateDeviceCodeStateConsumedByID, id)
	return err
}
