// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storeq

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type AuditLog struct {
	ID        int64
	UserID    uuid.NullUUID
	EventType string
	IpAddress pqtype.Inet
	UserAgent sql.NullString
	Metadata  pqtype.NullRawMessage
	CreatedAt time.Time
}

type AuthRequest struct {
	ID                  string
	ClientID            string
	Resource            sql.NullString
	RedirectUri         string
	Scopes              []string
	State               sql.NullString
	Nonce               sql.NullString
	CodeChallenge       sql.NullString
	CodeChallengeMethod sql.NullString
	Subject             sql.NullString
	AuthTime            sql.NullTime
	Done                bool
	Code                sql.NullString
	ExpiresAt           time.Time
	CreatedAt           time.Time
}

type CryptoKeyEpoch struct {
	KeyID       string
	Domain      string
	Status      string
	VerifyTag   string
	Version     int32
	CreatedAt   time.Time
	ActivatedAt sql.NullTime
	RetiredAt   sql.NullTime
	RevokedAt   sql.NullTime
}

type DeviceCode struct {
	ID           string
	DeviceCode   string
	UserCode     string
	ClientID     string
	Scopes       []string
	State        string
	Subject      sql.NullString
	ExpiresAt    time.Time
	AuthTime     sql.NullTime
	CreatedAt    time.Time
	LastPolledAt sql.NullTime
	Resource     sql.NullString
}

type RefreshToken struct {
	ID        string
	TokenHash string
	FamilyID  string
	UserID    string
	ClientID  string
	Resource  sql.NullString
	Scopes    []string
	ExpiresAt time.Time
	RevokedAt sql.NullTime
	UsedAt    sql.NullTime
	CreatedAt time.Time
}

type RefreshTokenFamily struct {
	FamilyID  string
	UserID    string
	Reason    string
	RevokedAt time.Time
}

type Session struct {
	ID        string
	UserID    string
	ExpiresAt time.Time
	RevokedAt sql.NullTime
	CreatedAt time.Time
	TokenHash sql.NullString
}

type User struct {
	ID                  string
	EmailVerified       bool
	Status              string
	DeletionRequestedAt sql.NullTime
	DeletionScheduledAt sql.NullTime
	DeletedAt           sql.NullTime
	CreatedAt           time.Time
	UpdatedAt           time.Time
	EmailCiphertext     []byte
	EmailNonce          []byte
	EmailEncKeyID       sql.NullString
	EmailEncVersion     sql.NullInt32
	EmailHash           sql.NullString
	EmailHashKeyID      sql.NullString
	EmailHashVersion    sql.NullInt32
	NameCiphertext      []byte
	NameNonce           []byte
	NameEncKeyID        sql.NullString
	NameEncVersion      sql.NullInt32
}

type UserIdentity struct {
	ID                     string
	UserID                 string
	Provider               string
	CreatedAt              time.Time
	ProviderSubHash        sql.NullString
	ProviderSubHashKeyID   sql.NullString
	ProviderSubHashVersion sql.NullInt32
	ProviderSubCiphertext  []byte
	ProviderSubNonce       []byte
	ProviderSubEncKeyID    sql.NullString
	ProviderSubEncVersion  sql.NullInt32
}
