// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storeq

import (
	"context"
	"database/sql"
	"time"
)

type Querier interface {
	AnonymizeAuditLogBefore(ctx context.Context, cutoff time.Time) (int64, error)
	ApproveDeviceCodeByUserCode(ctx context.Context, arg ApproveDeviceCodeByUserCodeParams) (int64, error)
	BackfillProviderSub(ctx context.Context, arg BackfillProviderSubParams) error
	BackfillUserPII(ctx context.Context, arg BackfillUserPIIParams) error
	CompleteAuthRequestByID(ctx context.Context, arg CompleteAuthRequestByIDParams) (int64, error)
	CountProviderSubUnbackfilled(ctx context.Context) (int64, error)
	CountUsersUnbackfilled(ctx context.Context) (int64, error)
	DeleteAuthRequestByID(ctx context.Context, id string) error
	DeleteExpiredAuthRequestsBefore(ctx context.Context, cutoff time.Time) (int64, error)
	DeleteExpiredDeviceCodesBefore(ctx context.Context, cutoff time.Time) (int64, error)
	DeleteExpiredOrRevokedSessions(ctx context.Context, cutoff time.Time) (int64, error)
	DeleteExpiredRefreshTokensBefore(ctx context.Context, cutoff time.Time) (int64, error)
	DeleteRefreshTokensByUserID(ctx context.Context, userID string) error
	DeleteRevokedRefreshTokensBefore(ctx context.Context, cutoff sql.NullTime) (int64, error)
	DeleteSessionsByUserID(ctx context.Context, userID string) error
	DeleteUserIdentitiesByUserID(ctx context.Context, userID string) error
	DenyDeviceCodeByUserCode(ctx context.Context, userCode string) error
	GetActiveEpoch(ctx context.Context, domain string) (GetActiveEpochRow, error)
	GetAuditClientContextBySessionID(ctx context.Context, arg GetAuditClientContextBySessionIDParams) (GetAuditClientContextBySessionIDRow, error)
	GetAuthRequestByCode(ctx context.Context, code sql.NullString) (GetAuthRequestByCodeRow, error)
	GetAuthRequestByID(ctx context.Context, id string) (GetAuthRequestByIDRow, error)
	GetDeviceAuthorizationForUpdate(ctx context.Context, arg GetDeviceAuthorizationForUpdateParams) (GetDeviceAuthorizationForUpdateRow, error)
	GetDeviceCodeByUserCode(ctx context.Context, userCode string) (GetDeviceCodeByUserCodeRow, error)
	GetRefreshFamilyIDByTokenHash(ctx context.Context, tokenHash string) (string, error)
	GetRefreshTokenForUpdateByHash(ctx context.Context, tokenHash string) (GetRefreshTokenForUpdateByHashRow, error)
	GetRefreshTokenInfoByHashAndClientID(ctx context.Context, arg GetRefreshTokenInfoByHashAndClientIDParams) (GetRefreshTokenInfoByHashAndClientIDRow, error)
	GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error)
	GetUserByProviderIdentity(ctx context.Context, arg GetUserByProviderIdentityParams) (GetUserByProviderIdentityRow, error)
	GetUserByProviderSubHash(ctx context.Context, arg GetUserByProviderSubHashParams) (GetUserByProviderSubHashRow, error)
	GetUserForTxByID(ctx context.Context, id string) (GetUserForTxByIDRow, error)
	GetUserInfoFieldsByID(ctx context.Context, id string) (GetUserInfoFieldsByIDRow, error)
	GetValidSessionUser(ctx context.Context, arg GetValidSessionUserParams) (GetValidSessionUserRow, error)
	InsertActiveEpoch(ctx context.Context, arg InsertActiveEpochParams) error
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	InsertAuthRequest(ctx context.Context, arg InsertAuthRequestParams) error
	InsertDeletionCompletedAudit(ctx context.Context, arg InsertDeletionCompletedAuditParams) error
	InsertDeviceCode(ctx context.Context, arg InsertDeviceCodeParams) error
	InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error
	InsertSession(ctx context.Context, arg InsertSessionParams) error
	InsertTestAuthRequest(ctx context.Context, arg InsertTestAuthRequestParams) error
	InsertTestAuthRequestWithResource(ctx context.Context, arg InsertTestAuthRequestWithResourceParams) error
	InsertUser(ctx context.Context, arg InsertUserParams) error
	InsertUserIdentity(ctx context.Context, arg InsertUserIdentityParams) error
	IsRefreshFamilyRevoked(ctx context.Context, familyID string) (bool, error)
	ListPendingDeletionUserIDsBefore(ctx context.Context, cutoff sql.NullTime) ([]string, error)
	ListProviderSubBackfill(ctx context.Context, limit int32) ([]ListProviderSubBackfillRow, error)
	ListUsersBackfill(ctx context.Context, limit int32) ([]ListUsersBackfillRow, error)
	MarkRefreshTokenUsedAndRevokedByID(ctx context.Context, arg MarkRefreshTokenUsedAndRevokedByIDParams) error
	// PII redaction on deletion (ADR-002): the plaintext tombstone replaces email,
	// and every encrypted/hashed email/name column is cleared so no recoverable PII
	// remains for the deleted user.
	MarkUserDeletedByID(ctx context.Context, arg MarkUserDeletedByIDParams) (int64, error)
	MarkUserPendingDeletionByID(ctx context.Context, arg MarkUserPendingDeletionByIDParams) (int64, error)
	RecoverPendingDeletionUserByID(ctx context.Context, arg RecoverPendingDeletionUserByIDParams) error
	RedactAuditLogPIIByUserID(ctx context.Context, userID string) (int64, error)
	RevokeActiveRefreshTokensByUserID(ctx context.Context, arg RevokeActiveRefreshTokensByUserIDParams) error
	RevokeRefreshFamily(ctx context.Context, arg RevokeRefreshFamilyParams) error
	RevokeRefreshTokenByHash(ctx context.Context, arg RevokeRefreshTokenByHashParams) (int64, error)
	RevokeRefreshTokenByID(ctx context.Context, arg RevokeRefreshTokenByIDParams) error
	RevokeSessionsByUserID(ctx context.Context, arg RevokeSessionsByUserIDParams) error
	SetUserStatusByID(ctx context.Context, arg SetUserStatusByIDParams) error
	TombstoneRefreshFamily(ctx context.Context, arg TombstoneRefreshFamilyParams) error
	TryCleanupAdvisoryLock(ctx context.Context, lockKey int64) (bool, error)
	UnlockCleanupAdvisoryLock(ctx context.Context, lockKey int64) (bool, error)
	UpdateAuthRequestCode(ctx context.Context, arg UpdateAuthRequestCodeParams) error
	UpdateDeviceCodeLastPolledAt(ctx context.Context, arg UpdateDeviceCodeLastPolledAtParams) error
	UpdateDeviceCodeStateConsumedByID(ctx context.Context, id string) error
}

var _ Querier = (*Queries)(nil)
