// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package storeq

import (
	"context"
	"database/sql"
)

type Querier interface {
	AnonymizeAuditLogBatch(ctx context.Context, arg AnonymizeAuditLogBatchParams) (int64, error)
	ApproveDeviceCodeByUserCode(ctx context.Context, arg ApproveDeviceCodeByUserCodeParams) (int64, error)
	CompleteAuthRequestByID(ctx context.Context, arg CompleteAuthRequestByIDParams) (int64, error)
	DeleteAuthRequestByID(ctx context.Context, id string) error
	DeleteExpiredAuthRequestsBatch(ctx context.Context, arg DeleteExpiredAuthRequestsBatchParams) (int64, error)
	DeleteExpiredDeviceCodesBatch(ctx context.Context, arg DeleteExpiredDeviceCodesBatchParams) (int64, error)
	DeleteExpiredOrRevokedSessionsBatch(ctx context.Context, arg DeleteExpiredOrRevokedSessionsBatchParams) (int64, error)
	DeleteExpiredRefreshTokensBatch(ctx context.Context, arg DeleteExpiredRefreshTokensBatchParams) (int64, error)
	DeleteRefreshTokensByUserID(ctx context.Context, userID string) error
	DeleteRevokedRefreshTokensBatch(ctx context.Context, arg DeleteRevokedRefreshTokensBatchParams) (int64, error)
	DeleteSessionsByUserID(ctx context.Context, userID string) error
	DeleteUserIdentitiesByUserID(ctx context.Context, userID string) error
	DenyDeviceCodeByUserCode(ctx context.Context, userCode string) error
	GetAuthRequestByCode(ctx context.Context, dollar_1 string) (GetAuthRequestByCodeRow, error)
	GetAuthRequestByID(ctx context.Context, id string) (GetAuthRequestByIDRow, error)
	GetDeviceAuthorizationForUpdate(ctx context.Context, arg GetDeviceAuthorizationForUpdateParams) (GetDeviceAuthorizationForUpdateRow, error)
	GetDeviceCodeByUserCode(ctx context.Context, userCode string) (GetDeviceCodeByUserCodeRow, error)
	GetRefreshFamilyIDByTokenHash(ctx context.Context, tokenHash string) (string, error)
	GetRefreshTokenForUpdateByHash(ctx context.Context, tokenHash string) (GetRefreshTokenForUpdateByHashRow, error)
	GetRefreshTokenInfoByHashAndClientID(ctx context.Context, arg GetRefreshTokenInfoByHashAndClientIDParams) (GetRefreshTokenInfoByHashAndClientIDRow, error)
	GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error)
	GetUserByProviderIdentity(ctx context.Context, arg GetUserByProviderIdentityParams) (GetUserByProviderIdentityRow, error)
	GetUserForTxByID(ctx context.Context, id string) (GetUserForTxByIDRow, error)
	GetUserInfoFieldsByID(ctx context.Context, id string) (GetUserInfoFieldsByIDRow, error)
	GetValidSessionUser(ctx context.Context, arg GetValidSessionUserParams) (GetValidSessionUserRow, error)
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	InsertAuthRequest(ctx context.Context, arg InsertAuthRequestParams) error
	InsertDeletionCompletedAudit(ctx context.Context, arg InsertDeletionCompletedAuditParams) error
	InsertDeviceCode(ctx context.Context, arg InsertDeviceCodeParams) error
	InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error
	InsertSession(ctx context.Context, arg InsertSessionParams) error
	InsertTestAuthRequest(ctx context.Context, arg InsertTestAuthRequestParams) error
	InsertUser(ctx context.Context, arg InsertUserParams) error
	InsertUserIdentity(ctx context.Context, arg InsertUserIdentityParams) error
	ListPendingDeletionUserIDsBefore(ctx context.Context, cutoff sql.NullTime) ([]string, error)
	MarkRefreshTokenUsedAndRevokedByID(ctx context.Context, arg MarkRefreshTokenUsedAndRevokedByIDParams) error
	MarkUserDeletedByID(ctx context.Context, arg MarkUserDeletedByIDParams) error
	MarkUserPendingDeletionByID(ctx context.Context, arg MarkUserPendingDeletionByIDParams) error
	RecoverPendingDeletionUserByID(ctx context.Context, arg RecoverPendingDeletionUserByIDParams) error
	RevokeActiveRefreshTokensByUserID(ctx context.Context, arg RevokeActiveRefreshTokensByUserIDParams) error
	RevokeRefreshFamily(ctx context.Context, arg RevokeRefreshFamilyParams) error
	RevokeRefreshTokenByHash(ctx context.Context, arg RevokeRefreshTokenByHashParams) (int64, error)
	RevokeRefreshTokenByIDText(ctx context.Context, arg RevokeRefreshTokenByIDTextParams) error
	RevokeSessionsByUserID(ctx context.Context, arg RevokeSessionsByUserIDParams) error
	SetUserStatusByID(ctx context.Context, arg SetUserStatusByIDParams) error
	UpdateAuthRequestCode(ctx context.Context, arg UpdateAuthRequestCodeParams) error
	UpdateDeviceCodeStateConsumedByID(ctx context.Context, id string) error
}

var _ Querier = (*Queries)(nil)
