// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package storeq

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const countRefreshTokenChildren = `-- name: CountRefreshTokenChildren :one
SELECT count(*)
FROM refresh_tokens
WHERE parent_id = $1::uuid
`

func (q *Queries) CountRefreshTokenChildren(ctx context.Context, parentID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRefreshTokenChildren, parentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getRefreshFamilyIDByTokenHash = `-- name: GetRefreshFamilyIDByTokenHash :one
SELECT family_id
FROM refresh_tokens
WHERE token_hash = $1
`

func (q *Queries) GetRefreshFamilyIDByTokenHash(ctx context.Context, tokenHash string) (string, error) {
	row := q.db.QueryRowContext(ctx, getRefreshFamilyIDByTokenHash, tokenHash)
	var family_id string
	err := row.Scan(&family_id)
	return family_id, err
}

const getRefreshTokenForUpdateByHash = `-- name: GetRefreshTokenForUpdateByHash :one
SELECT id, token_hash, family_id, user_id, client_id, COALESCE(resource, '') AS resource,
       scopes, expires_at, revoked_at, used_at
FROM refresh_tokens
WHERE token_hash = $1
FOR UPDATE
`

type GetRefreshTokenForUpdateByHashRow struct {
	ID        string
	TokenHash string
	FamilyID  string
	UserID    string
	ClientID  string
	Resource  string
	Scopes    []string
	ExpiresAt time.Time
	RevokedAt sql.NullTime
	UsedAt    sql.NullTime
}

func (q *Queries) GetRefreshTokenForUpdateByHash(ctx context.Context, tokenHash string) (GetRefreshTokenForUpdateByHashRow, error) {
	row := q.db.QueryRowContext(ctx, getRefreshTokenForUpdateByHash, tokenHash)
	var i GetRefreshTokenForUpdateByHashRow
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.FamilyID,
		&i.UserID,
		&i.ClientID,
		&i.Resource,
		pq.Array(&i.Scopes),
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UsedAt,
	)
	return i, err
}

const getRefreshTokenGrantByHash = `-- name: GetRefreshTokenGrantByHash :one
SELECT family_id, user_id
FROM refresh_tokens
WHERE token_hash = $1 AND client_id = $2
`

type GetRefreshTokenGrantByHashParams struct {
	TokenHash string
	ClientID  string
}

type GetRefreshTokenGrantByHashRow struct {
	FamilyID string
	UserID   string
}

// Scoped to the client: RFC 7009 §2.1 revokes only tokens issued to the
// requesting client.
func (q *Queries) GetRefreshTokenGrantByHash(ctx context.Context, arg GetRefreshTokenGrantByHashParams) (GetRefreshTokenGrantByHashRow, error) {
	row := q.db.QueryRowContext(ctx, getRefreshTokenGrantByHash, arg.TokenHash, arg.ClientID)
	var i GetRefreshTokenGrantByHashRow
	err := row.Scan(&i.FamilyID, &i.UserID)
	return i, err
}

const getRefreshTokenGrantByID = `-- name: GetRefreshTokenGrantByID :one
SELECT family_id, user_id
FROM refresh_tokens
WHERE id = $1 AND client_id = $2
`

type GetRefreshTokenGrantByIDParams struct {
	ID       string
	ClientID string
}

type GetRefreshTokenGrantByIDRow struct {
	FamilyID string
	UserID   string
}

func (q *Queries) GetRefreshTokenGrantByID(ctx context.Context, arg GetRefreshTokenGrantByIDParams) (GetRefreshTokenGrantByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getRefreshTokenGrantByID, arg.ID, arg.ClientID)
	var i GetRefreshTokenGrantByIDRow
	err := row.Scan(&i.FamilyID, &i.UserID)
	return i, err
}

const getRefreshTokenInfoByHashAndClientID = `-- name: GetRefreshTokenInfoByHashAndClientID :one
SELECT user_id, id
FROM refresh_tokens
WHERE token_hash = $1 AND client_id = $2
`

type GetRefreshTokenInfoByHashAndClientIDParams struct {
	TokenHash string
	ClientID  string
}

type GetRefreshTokenInfoByHashAndClientIDRow struct {
	UserID string
	ID     string
}

func (q *Queries) GetRefreshTokenInfoByHashAndClientID(ctx context.Context, arg GetRefreshTokenInfoByHashAndClientIDParams) (GetRefreshTokenInfoByHashAndClientIDRow, error) {
	row := q.db.QueryRowContext(ctx, getRefreshTokenInfoByHashAndClientID, arg.TokenHash, arg.ClientID)
	var i GetRefreshTokenInfoByHashAndClientIDRow
	err := row.Scan(&i.UserID, &i.ID)
	return i, err
}

const hasRevokedUnredeemedRefreshTokenInFamily = `-- name: HasRevokedUnredeemedRefreshTokenInFamily :one
SELECT EXISTS (
    SELECT 1 FROM refresh_tokens
    WHERE family_id = $1 AND revoked_at IS NOT NULL AND used_at IS NULL
) AS revoked
`

// A token revoked without being redeemed was revoked on purpose (/oauth/revoke,
// a user-wide revoke, reuse detection). Rotation always sets used_at together
// with revoked_at.
func (q *Queries) HasRevokedUnredeemedRefreshTokenInFamily(ctx context.Context, familyID string) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasRevokedUnredeemedRefreshTokenInFamily, familyID)
	var revoked bool
	err := row.Scan(&revoked)
	return revoked, err
}

const insertRefreshToken = `-- name: InsertRefreshToken :exec
INSERT INTO refresh_tokens (id, token_hash, family_id, user_id, client_id, resource, scopes, expires_at, created_at, parent_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertRefreshTokenParams struct {
	ID        string
	TokenHash string
	FamilyID  string
	UserID    string
	ClientID  string
	Resource  sql.NullString
	Scopes    []string
	ExpiresAt time.Time
	CreatedAt time.Time
	ParentID  uuid.NullUUID
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, insertRefreshToken,
		arg.ID,
		arg.TokenHash,
		arg.FamilyID,
		arg.UserID,
		arg.ClientID,
		arg.Resource,
		pq.Array(arg.Scopes),
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.ParentID,
	)
	return err
}

const isRefreshFamilyRevoked = `-- name: IsRefreshFamilyRevoked :one
SELECT EXISTS (
    SELECT 1 FROM refresh_token_families WHERE family_id = $1
) AS revoked
`

func (q *Queries) IsRefreshFamilyRevoked(ctx context.Context, familyID string) (bool, error) {
	row := q.db.QueryRowContext(ctx, isRefreshFamilyRevoked, familyID)
	var revoked bool
	err := row.Scan(&revoked)
	return revoked, err
}

const lockRefreshFamily = `-- name: LockRefreshFamily :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, 0))
`

// All rotation/reuse/revoke transactions take the family lock before any row
// lock. Hash collisions only serialize unrelated families; no grant is mixed.
func (q *Queries) LockRefreshFamily(ctx context.Context, familyID string) error {
	_, err := q.db.ExecContext(ctx, lockRefreshFamily, familyID)
	return err
}

const markRefreshTokenUsedAndRevokedByID = `-- name: MarkRefreshTokenUsedAndRevokedByID :exec
UPDATE refresh_tokens
SET used_at = $1, revoked_at = $1
WHERE id = $2
`

type MarkRefreshTokenUsedAndRevokedByIDParams struct {
	UsedAt sql.NullTime
	ID     string
}

func (q *Queries) MarkRefreshTokenUsedAndRevokedByID(ctx context.Context, arg MarkRefreshTokenUsedAndRevokedByIDParams) error {
	_, err := q.db.ExecContext(ctx, markRefreshTokenUsedAndRevokedByID, arg.UsedAt, arg.ID)
	return err
}

const revokeRefreshFamily = `-- name: RevokeRefreshFamily :execrows
UPDATE refresh_tokens
SET revoked_at = $1
WHERE family_id = $2 AND revoked_at IS NULL
`

type RevokeRefreshFamilyParams struct {
	RevokedAt sql.NullTime
	FamilyID  string
}

func (q *Queries) RevokeRefreshFamily(ctx context.Context, arg RevokeRefreshFamilyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeRefreshFamily, arg.RevokedAt, arg.FamilyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeRefreshTokenByHash = `-- name: RevokeRefreshTokenByHash :execrows
UPDATE refresh_tokens
SET revoked_at = $1
WHERE token_hash = $2 AND revoked_at IS NULL
`

type RevokeRefreshTokenByHashParams struct {
	RevokedAt sql.NullTime
	TokenHash string
}

// Revocation leaves used_at alone: used_at is set only when the token is
// redeemed at the token endpoint, which is what refresh reuse grace relies on
// to tell a rotated token from a revoked one.
func (q *Queries) RevokeRefreshTokenByHash(ctx context.Context, arg RevokeRefreshTokenByHashParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeRefreshTokenByHash, arg.RevokedAt, arg.TokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const tombstoneRefreshFamily = `-- name: TombstoneRefreshFamily :execrows
INSERT INTO refresh_token_families (family_id, user_id, reason, revoked_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (family_id) DO NOTHING
`

type TombstoneRefreshFamilyParams struct {
	FamilyID  string
	UserID    string
	Reason    string
	RevokedAt time.Time
}

func (q *Queries) TombstoneRefreshFamily(ctx context.Context, arg TombstoneRefreshFamilyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, tombstoneRefreshFamily,
		arg.FamilyID,
		arg.UserID,
		arg.Reason,
		arg.RevokedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
