// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package storeq

import (
	"context"
	"database/sql"
	"time"
)

const getValidSessionUser = `-- name: GetValidSessionUser :one
SELECT u.id, u.email, u.email_verified, u.name, u.status,
       u.email_ciphertext, u.email_nonce, u.email_enc_key_id, u.email_enc_version,
       u.name_ciphertext, u.name_nonce, u.name_enc_key_id, u.name_enc_version,
       u.created_at, u.updated_at
FROM sessions s
JOIN users u ON s.user_id = u.id
WHERE s.token_hash = $1::text
  AND s.expires_at > $2
  AND s.revoked_at IS NULL
`

type GetValidSessionUserParams struct {
	TokenHash string
	ExpiresAt time.Time
}

type GetValidSessionUserRow struct {
	ID              string
	Email           sql.NullString
	EmailVerified   bool
	Name            sql.NullString
	Status          string
	EmailCiphertext []byte
	EmailNonce      []byte
	EmailEncKeyID   sql.NullString
	EmailEncVersion sql.NullInt32
	NameCiphertext  []byte
	NameNonce       []byte
	NameEncKeyID    sql.NullString
	NameEncVersion  sql.NullInt32
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) GetValidSessionUser(ctx context.Context, arg GetValidSessionUserParams) (GetValidSessionUserRow, error) {
	row := q.db.QueryRowContext(ctx, getValidSessionUser, arg.TokenHash, arg.ExpiresAt)
	var i GetValidSessionUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.Name,
		&i.Status,
		&i.EmailCiphertext,
		&i.EmailNonce,
		&i.EmailEncKeyID,
		&i.EmailEncVersion,
		&i.NameCiphertext,
		&i.NameNonce,
		&i.NameEncKeyID,
		&i.NameEncVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO sessions (id, user_id, token_hash, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertSessionParams struct {
	ID        string
	UserID    string
	TokenHash sql.NullString
	ExpiresAt time.Time
	CreatedAt time.Time
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.ExecContext(ctx, insertSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const revokeSessionsByUserID = `-- name: RevokeSessionsByUserID :exec
UPDATE sessions
SET revoked_at = $1
WHERE user_id = $2 AND revoked_at IS NULL
`

type RevokeSessionsByUserIDParams struct {
	RevokedAt sql.NullTime
	UserID    string
}

func (q *Queries) RevokeSessionsByUserID(ctx context.Context, arg RevokeSessionsByUserIDParams) error {
	_, err := q.db.ExecContext(ctx, revokeSessionsByUserID, arg.RevokedAt, arg.UserID)
	return err
}
