// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package storeq

import (
	"context"
	"database/sql"
	"time"
)

const completeAuthRequestByID = `-- name: CompleteAuthRequestByID :execrows
UPDATE auth_requests
SET subject = $1, auth_time = $2, done = true
WHERE id = $3 AND expires_at > $2
`

type CompleteAuthRequestByIDParams struct {
	Subject  sql.NullString
	AuthTime sql.NullTime
	ID       string
}

func (q *Queries) CompleteAuthRequestByID(ctx context.Context, arg CompleteAuthRequestByIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeAuthRequestByID, arg.Subject, arg.AuthTime, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, email_verified, name, avatar_url, status,
       created_at, updated_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID            string
	Email         string
	EmailVerified bool
	Name          sql.NullString
	AvatarUrl     sql.NullString
	Status        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.Name,
		&i.AvatarUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByProviderIdentity = `-- name: GetUserByProviderIdentity :one
SELECT u.id, u.email, u.email_verified, u.name, u.avatar_url, u.status,
       u.created_at, u.updated_at
FROM users u
JOIN user_identities ui ON u.id = ui.user_id
WHERE ui.provider = $1 AND ui.provider_user_id = $2
`

type GetUserByProviderIdentityParams struct {
	Provider       string
	ProviderUserID string
}

type GetUserByProviderIdentityRow struct {
	ID            string
	Email         string
	EmailVerified bool
	Name          sql.NullString
	AvatarUrl     sql.NullString
	Status        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) GetUserByProviderIdentity(ctx context.Context, arg GetUserByProviderIdentityParams) (GetUserByProviderIdentityRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByProviderIdentity, arg.Provider, arg.ProviderUserID)
	var i GetUserByProviderIdentityRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.Name,
		&i.AvatarUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserForTxByID = `-- name: GetUserForTxByID :one
SELECT id, email, email_verified, name, status
FROM users
WHERE id = $1
`

type GetUserForTxByIDRow struct {
	ID            string
	Email         string
	EmailVerified bool
	Name          sql.NullString
	Status        string
}

func (q *Queries) GetUserForTxByID(ctx context.Context, id string) (GetUserForTxByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserForTxByID, id)
	var i GetUserForTxByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.Name,
		&i.Status,
	)
	return i, err
}

const getUserInfoFieldsByID = `-- name: GetUserInfoFieldsByID :one
SELECT id, email, email_verified, name
FROM users
WHERE id = $1
`

type GetUserInfoFieldsByIDRow struct {
	ID            string
	Email         string
	EmailVerified bool
	Name          sql.NullString
}

func (q *Queries) GetUserInfoFieldsByID(ctx context.Context, id string) (GetUserInfoFieldsByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserInfoFieldsByID, id)
	var i GetUserInfoFieldsByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.Name,
	)
	return i, err
}

const insertTestAuthRequest = `-- name: InsertTestAuthRequest :exec
INSERT INTO auth_requests (
  id,
  client_id,
  redirect_uri,
  scopes,
  state,
  nonce,
  code_challenge,
  code_challenge_method,
  expires_at,
  created_at
)
VALUES (
  $1,
  'test-app',
  'http://localhost/callback',
  '{openid}',
  $2,
  'test-nonce',
  'E9Melhoa2OwvFrEMT',
  'S256',
  $3,
  $4
)
`

type InsertTestAuthRequestParams struct {
	ID        string
	State     sql.NullString
	ExpiresAt time.Time
	CreatedAt time.Time
}

func (q *Queries) InsertTestAuthRequest(ctx context.Context, arg InsertTestAuthRequestParams) error {
	_, err := q.db.ExecContext(ctx, insertTestAuthRequest,
		arg.ID,
		arg.State,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const insertTestAuthRequestWithResource = `-- name: InsertTestAuthRequestWithResource :exec
INSERT INTO auth_requests (
  id,
  client_id,
  redirect_uri,
  scopes,
  state,
  nonce,
  code_challenge,
  code_challenge_method,
  resource,
  expires_at,
  created_at
)
VALUES (
  $1,
  'test-app',
  'http://localhost/callback',
  '{openid}',
  $2,
  'test-nonce',
  'E9Melhoa2OwvFrEMT',
  'S256',
  $3,
  $4,
  $5
)
`

type InsertTestAuthRequestWithResourceParams struct {
	ID        string
	State     sql.NullString
	Resource  sql.NullString
	ExpiresAt time.Time
	CreatedAt time.Time
}

func (q *Queries) InsertTestAuthRequestWithResource(ctx context.Context, arg InsertTestAuthRequestWithResourceParams) error {
	_, err := q.db.ExecContext(ctx, insertTestAuthRequestWithResource,
		arg.ID,
		arg.State,
		arg.Resource,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO users (id, email, email_verified, name, avatar_url, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, 'active', $6, $6)
`

type InsertUserParams struct {
	ID            string
	Email         string
	EmailVerified bool
	Name          sql.NullString
	AvatarUrl     sql.NullString
	CreatedAt     time.Time
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.ExecContext(ctx, insertUser,
		arg.ID,
		arg.Email,
		arg.EmailVerified,
		arg.Name,
		arg.AvatarUrl,
		arg.CreatedAt,
	)
	return err
}

const insertUserIdentity = `-- name: InsertUserIdentity :exec
INSERT INTO user_identities (id, user_id, provider, provider_user_id, provider_email, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertUserIdentityParams struct {
	ID             string
	UserID         string
	Provider       string
	ProviderUserID string
	ProviderEmail  sql.NullString
	CreatedAt      time.Time
}

func (q *Queries) InsertUserIdentity(ctx context.Context, arg InsertUserIdentityParams) error {
	_, err := q.db.ExecContext(ctx, insertUserIdentity,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserID,
		arg.ProviderEmail,
		arg.CreatedAt,
	)
	return err
}

const markUserPendingDeletionByID = `-- name: MarkUserPendingDeletionByID :exec
UPDATE users
SET status = 'pending_deletion',
    deletion_requested_at = $1,
    deletion_scheduled_at = $2,
    updated_at = $1
WHERE id = $3
`

type MarkUserPendingDeletionByIDParams struct {
	DeletionRequestedAt sql.NullTime
	DeletionScheduledAt sql.NullTime
	ID                  string
}

func (q *Queries) MarkUserPendingDeletionByID(ctx context.Context, arg MarkUserPendingDeletionByIDParams) error {
	_, err := q.db.ExecContext(ctx, markUserPendingDeletionByID, arg.DeletionRequestedAt, arg.DeletionScheduledAt, arg.ID)
	return err
}

const recoverPendingDeletionUserByID = `-- name: RecoverPendingDeletionUserByID :exec
UPDATE users
SET status = 'active',
    deletion_requested_at = NULL,
    deletion_scheduled_at = NULL,
    updated_at = $1
WHERE id = $2 AND status = 'pending_deletion'
`

type RecoverPendingDeletionUserByIDParams struct {
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) RecoverPendingDeletionUserByID(ctx context.Context, arg RecoverPendingDeletionUserByIDParams) error {
	_, err := q.db.ExecContext(ctx, recoverPendingDeletionUserByID, arg.UpdatedAt, arg.ID)
	return err
}

const revokeActiveRefreshTokensByUserID = `-- name: RevokeActiveRefreshTokensByUserID :exec
UPDATE refresh_tokens
SET revoked_at = $1
WHERE user_id = $2 AND revoked_at IS NULL
`

type RevokeActiveRefreshTokensByUserIDParams struct {
	RevokedAt sql.NullTime
	UserID    string
}

func (q *Queries) RevokeActiveRefreshTokensByUserID(ctx context.Context, arg RevokeActiveRefreshTokensByUserIDParams) error {
	_, err := q.db.ExecContext(ctx, revokeActiveRefreshTokensByUserID, arg.RevokedAt, arg.UserID)
	return err
}

const setUserStatusByID = `-- name: SetUserStatusByID :exec
UPDATE users
SET status = $1, updated_at = $2
WHERE id = $3
`

type SetUserStatusByIDParams struct {
	Status    string
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) SetUserStatusByID(ctx context.Context, arg SetUserStatusByIDParams) error {
	_, err := q.db.ExecContext(ctx, setUserStatusByID, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}
