apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "authgate.fullname" . }}-clients
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "authgate.labels" . | nindent 4 }}
data:
  clients.yaml: |
{{- if .Values.clients.clients }}
{{ toYaml (dict "clients" .Values.clients.clients) | indent 4 }}
{{- else }}
    clients: []
{{- end }}
