{{- if .Values.postgresql.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "authgate.postgres.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "authgate.postgres.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.postgresql.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "authgate.postgres.selectorLabels" . | nindent 4 }}
{{- end }}
