{{- if .Values.postgresql.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "authgate.postgres.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "authgate.postgres.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "authgate.postgres.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "authgate.postgres.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "authgate.postgres.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.postgresql.podSecurityContext | nindent 8 }}
      containers:
        - name: postgres
          image: {{ .Values.postgresql.image }}
          imagePullPolicy: {{ .Values.postgresql.imagePullPolicy }}
          securityContext:
            {{- toYaml .Values.postgresql.securityContext | nindent 12 }}
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.auth.database | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.auth.username | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "authgate.postgres.secretName" . }}
                  key: postgres-password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.postgresql.auth.username | quote }}
                - -d
                - {{ .Values.postgresql.auth.database | quote }}
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.postgresql.auth.username | quote }}
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          resources:
            {{- toYaml .Values.postgresql.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          {{- include "authgate.postgres.labels" . | nindent 10 }}
      spec:
        accessModes:
          - {{ .Values.postgresql.storage.accessMode }}
        resources:
          requests:
            storage: {{ .Values.postgresql.storage.size }}
        {{- with .Values.postgresql.storage.storageClass }}
        storageClassName: {{ . }}
        {{- end }}
{{- end }}
